### ISSUE TITLE
Can not find the uci dataset

### ISSUE THREAD

**Issue by momocat-aric** [kingfengji/mGBDT#1]
Hi,
I wanna run the uci_year and uci_adult demo,  but I can't find the get_data.sh files as ReadME said. Would you please upload it or tell me the data format so I can handle it by myself. 
I find that the code uses features file, but it is not in the git too.

**Comment by momocat-aric** [comment]
Should I flattening all the properties of one smaple in a one-hot vector?

**Comment by kingfengji** [comment]
@AricPro thanks for pointing it out, I've uploaded the get_data script to the repo.
